var arr = [
    {
        "_id":"womens_clothing","startUrl":["https://www.shop.com/Clothes/Women-36?m=Women%27s+Clothing+Type"],
        "selectors":[{"id":"category_link",
        "parentSelectors":["_root"],
        "type":"SelectorLink",
        "selector":"a.qa-search-filter-link",
        "multiple":true},
        {"id":"subcategory_link",
        "parentSelectors":["category_link"],
        "type":"SelectorLink",
        "selector":"ul:nth-of-type(2) a.qa-search-filter-link",
        "multiple":true},
        {"id":"product_link",
        "parentSelectors":["subcategory_link"],
        "type":"SelectorLink",
        "selector":".product-results__prod-title--full a",
        "multiple":true},
        {"id":"name",
        "parentSelectors":["product_link"],
        "type":"SelectorText",
        "selector":".product__header-main h1",
        "multiple":false,
        "regex":""},
        {"id":"soldby",
        "parentSelectors":["product_link"],
        "type":"SelectorText",
        "selector":".product__header-main p.product__sold-by",
        "multiple":false,
        "regex":""},
        {"id":"price",
        "parentSelectors":["product_link"],
        "type":"SelectorText",
        "selector":"p.qa-product-price",
        "multiple":false,
        "regex":""},
        {"id":"size",
        "parentSelectors":["product_link"],
        "type":"SelectorText",
        "selector":"li.option:nth-of-type(n+2)",
        "multiple":true,
        "regex":""},
        {"id":"about",
        "parentSelectors":["product_link"],
        "type":"SelectorText",
        "selector":".wrapper--large p",
        "multiple":false,
        "regex":""},
        {"id":"image",
        "parentSelectors":["product_link"],
        "type":"SelectorImage",
        "selector":"img.js-main-image",
        "multiple":false}
    ]}   
    
];